output = "internal/models"
wipe = true
no-tests = true

[psql]
dbname = "roddbot_db"
port = 5432
user = "roddbot_admin"
pass = "password"
sslmode = "disable"
host = "localhost"
blacklist = ["schema_migrations"]