// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ChallChannels     string
	CTFChannels       string
	GuildRoleMappings string
	Guilds            string
}{
	ChallChannels:     "chall_channels",
	CTFChannels:       "ctf_channels",
	GuildRoleMappings: "guild_role_mappings",
	Guilds:            "guilds",
}
